baseURL = "http://cunger.github.io"
languageCode = "en-gb"
defaultContentLanguage = "en"

title = "Escape Velocity"

Paginate = 4
[Params]
  description = "Getting up to speed and accelerating."
  author = "Christina Unger"
  github = "cunger"
  email = "christina@unger.dev"

[[menu.main]]
    name = "Notebooks"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "ğŸ‡ğŸ•³ï¸"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "About"
    weight = -100
    url = "/about"

# Code syntax highlighting

# pygmentsCodeFences = true

[markup]
  markup = "mmark"

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 2
